language: minimal

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t feed udacity-c3-restapi-feed/ 
  - docker tag feed iravi89/feed:latest
  - docker build -t feed udacity-c3-restapi-user/
  - docker tag feed iravi89/user:latest
  - docker build -t feed udacity-c3-frontend/
  - docker tag feed iravi89/frontend:latest
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "iravi89" --password-stdin
  - docker push iravi89/feed
  - docker push iravi89/user
  - docker push iravi89/frontend
